version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/browser-tests"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
      - dependency-name: "@govuk-one-login/data-vocab" # ignore until data-vocab is published to public npm registry, or we add token here
    open-pull-requests-limit: 10
    commit-message:
      prefix: BAU
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    ignore:
      - dependency-name: "node"
        versions: [ ">=22.x" ]
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    commit-message:
      prefix: BAU
