version: 2
updates:
  - package-ecosystem: "npm"
    directories:
      - "/"
      - "/browser-tests"
    registries: "*"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-patch" ]
    open-pull-requests-limit: 10
    commit-message:
      prefix: BAU
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    commit-message:
      prefix: BAU
    groups:
      codeql:
        patterns:
          - "github/codeql-action"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    target-branch: main
    labels:
    - dependabot
    commit-message:
      prefix: BAU
    groups:
      pre-commit:
        patterns:
          - "*"
