all: true
check-coverage: true
include:
  - "src/**/*.ts"
exclude:
  - "**/*.test.ts"
  - "**/*router.ts"
  - "src/app.ts"
  - "src/config/*"
report-dir: coverage
statements: 80
branches: 80
functions: 80
lines: 80
watermarks:
  statements:
    - 80
    - 90
  branches:
    - 80
    - 90
  functions:
    - 80
    - 90
  lines:
    - 80
    - 90
