module.exports = Object.freeze({
  CONFIRM_ADDRESS: "confirm-address",
  CONFIRM_NAME_DATE_BIRTH: "confirm-name-date-birth",
  CONFIRM_DETAILS: "confirm-your-details",
  NO_PHOTO_ID_EXIT_FIND_ANOTHER_WAY: "no-photo-id-exit-find-another-way",
  NO_PHOTO_ID_SECURITY_QUESTIONS_FIND_ANOTHER_WAY:
    "no-photo-id-security-questions-find-another-way",
  PAGE_DCMAW_SUCCESS: "page-dcmaw-success",
  PAGE_FACE_TO_FACE_HANDOFF: "page-face-to-face-handoff",
  PAGE_IPV_IDENTITY_DOCUMENT_START: "page-ipv-identity-document-start",
  PAGE_IPV_IDENTITY_POST_OFFICE_START: "page-ipv-identity-postoffice-start",
  PAGE_IPV_PENDING: "page-ipv-pending",
  PAGE_IPV_REUSE: "page-ipv-reuse",
  PAGE_IPV_SUCCESS: "page-ipv-success",
  PAGE_MULTIPLE_DOC_CHECK: "page-multiple-doc-check",
  PAGE_PRE_EXPERIAN_KBV_TRANSITION: "page-pre-experian-kbv-transition",
  PROVE_IDENTITY_BANK_ACCOUNT: "prove-identity-bank-account",
  PYI_ANOTHER_WAY: "pyi-another-way",
  PYI_ATTEMPT_RECOVERY: "pyi-attempt-recovery",
  PYI_CONFIRM_DELETE_DETAILS: "pyi-confirm-delete-details",
  PYI_CONTINUE_WITH_DRIVING_LICENCE: "pyi-continue-with-driving-licence",
  PYI_CONTINUE_WITH_PASSPORT: "pyi-continue-with-passport",
  PYI_CRI_ESCAPE: "pyi-cri-escape",
  PYI_CRI_ESCAPE_NO_F2F: "pyi-cri-escape-no-f2f",
  PYI_DETAILS_DELETED: "pyi-details-deleted",
  PYI_DRIVING_LICENCE_NO_MATCH: "pyi-driving-licence-no-match",
  PYI_DRIVING_LICENCE_NO_MATCH_ANOTHER_WAY:
    "pyi-driving-licence-no-match-another-way",
  PYI_ESCAPE: "pyi-escape",
  PYI_F2F_DELETE_DETAILS: "pyi-f2f-delete-details",
  PYI_F2F_TECHNICAL: "pyi-f2f-technical",
  PYI_NEW_DETAILS: "pyi-new-details",
  PYI_NO_MATCH: "pyi-no-match",
  PYI_PASSPORT_NO_MATCH: "pyi-passport-no-match",
  PYI_PASSPORT_NO_MATCH_ANOTHER_WAY: "pyi-passport-no-match-another-way",
  PYI_POST_OFFICE: "pyi-post-office",
  PYI_SUGGEST_OTHER_OPTIONS: "pyi-suggest-other-options",
  PYI_SUGGEST_OTHER_OPTIONS_NO_F2F: "pyi-suggest-other-options-no-f2f",
  PYI_TECHNICAL: "pyi-technical",
  PYI_TIMEOUT_RECOVERABLE: "pyi-timeout-recoverable",
  PYI_TIMEOUT_UNRECOVERABLE: "pyi-timeout-unrecoverable",
  PYI_TRIAGE_DESKTOP_DOWNLOAD_APP: "pyi-triage-desktop-download-app",
  PYI_TRIAGE_MOBILE_DOWNLOAD_APP: "pyi-triage-mobile-download-app",
  PYI_TRIAGE_SELECT_DEVICE: "pyi-triage-select-device",
  PYI_TRIAGE_SELECT_SMARTPHONE: "pyi-triage-select-smartphone",
  UPDATE_DETAILS: "update-details",
  UPDATE_NAME_DATE_BIRTH: "update-name-date-birth",
});
