FrontLoadBalancer5xxErrors:
  Type: AWS::CloudWatch::Alarm
  Condition: IsNotDevelopment
  Properties:
    AlarmName: FrontLoadBalancer5xxAlarm
    ActionsEnabled: true
    AlarmActions:
      - !ImportValue sns-topics-AlarmTopic
    OKActions:
      - !ImportValue sns-topics-AlarmTopic
    InsufficientDataActions: []
    EvaluationPeriods: 2
    DatapointsToAlarm: 2
    Threshold: !FindInMap [ EnvironmentConfiguration, !Ref AWS::AccountId, lb500ErrorLimit ]
    ComparisonOperator: GreaterThanOrEqualToThreshold
    TreatMissingData: notBreaching
    Metrics:
      - Id: e1
        Label: Sum-of-5xx-Errors
        ReturnData: true
        Expression: SUM(METRICS())
      - Id: m1
        ReturnData: false
        MetricStat:
          Metric:
            Namespace: AWS/ApplicationELB
            MetricName: HTTPCode_ELB_5XX_Count
            Dimensions:
              - Name: LoadBalancer
                Value: !GetAtt PrivateLoadBalancer.LoadBalancerFullName
          Period: !FindInMap [ EnvironmentConfiguration, !Ref AWS::AccountId, lb500ErrorWindow ]
          Stat: Sum

FrontTargetGroup5xxErrors:
  Type: AWS::CloudWatch::Alarm
  Condition: IsNotDevelopment
  Properties:
    AlarmName: FrontTargetGroup5xxAlarm
    ActionsEnabled: true
    AlarmActions:
      - !ImportValue sns-topics-AlarmTopic
    OKActions:
      - !ImportValue sns-topics-AlarmTopic
    InsufficientDataActions: [ ]
    EvaluationPeriods: 2
    DatapointsToAlarm: 2
    Threshold: !FindInMap [ EnvironmentConfiguration, !Ref AWS::AccountId, tg500ErrorLimit ]
    ComparisonOperator: GreaterThanOrEqualToThreshold
    TreatMissingData: notBreaching
    Metrics:
      - Id: e1
        Label: Sum-of-5xx-Errors
        ReturnData: true
        Expression: SUM(METRICS())
      - Id: m1
        ReturnData: false
        MetricStat:
          Metric:
            Namespace: AWS/ApplicationELB
            MetricName: HTTPCode_Target_5XX_Count
            Dimensions:
              - Name: LoadBalancer
                Value: !GetAtt PrivateLoadBalancer.LoadBalancerFullName
          Period: !FindInMap [ EnvironmentConfiguration, !Ref AWS::AccountId, tg500ErrorWindow ]
          Stat: Sum

### Lambda metrics with session ID as dimension
LambdaInvocationsBySessId:
  Type: AWS::Logs::LogGroup
  Properties:
    RetentionInDays: 90
    LogGroupName: !Sub LambdaInvocationsBySessId-${Environment}

BuildClientOAuthResponseInvocationsBySessId:
  Type: AWS::Logs::MetricFilter
  Properties:
    FilterName: BuildClientOAuthResponseInvocationsBySessId
    FilterPattern: ipvSessionId
    LogGroupName: !Ref LambdaInvocationsBySessionId
    MetricTransformations:
      - DefaultValue: 0
        Dimensions:
          Key: ipvSessionId
          Value: $.ipvSessionId
        MetricName: !Sub BuildClientOAuthResponseInvocationsBySessId-${Environment}
        MetricValue: 1
        Unit: Count

#LambdasOutOfSync:
#  Type: AWS::CloudWatch::Alarm
#  Condition: IsNotDevelopment
#  Properties:
#    AlarmName: LambdasOutOfSync
#    ActionsEnabled: true
#    AlarmActions:
#      - !ImportValue sns-topics-AlarmTopic
#    OKActions:
#      - !ImportValue sns-topics-AlarmTopic
#    InsufficientDataActions: [ ]
#    EvaluationPeriods: 2
#    DatapointsToAlarm: 2
#    Threshold:
#    ComparisonOperator: GreaterThanOrEqualToThreshold
#    TreatMissingData: notBreaching
#    Metrics:
#      - Id: e1
#        Label: Sum-of-5xx-Errors
#        ReturnData: true
#        Expression: SUM(METRICS())
#      - Id: m1
#        ReturnData: false
#        MetricStat:
#          Metric:
#            Namespace: AWS/ApplicationELB
#            MetricName: HTTPCode_Target_5XX_Count
#            Dimensions:
#              - Name: LoadBalancer
#                Value: !GetAtt PrivateLoadBalancer.LoadBalancerFullName
#          Period: !FindInMap [ EnvironmentConfiguration, !Ref AWS::AccountId, tg500ErrorWindow ]
#          Stat: Sum
