name: Pre-merge checks
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
          cache: 'yarn'
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
      - name: Install dependencies
        run: yarn install
      - name: Run lint
        run: yarn lint
      - name: Run test and write coverage
        run: yarn test:coverage
      - name: Run sonarcloud scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # obtained from https://sonarcloud.io
      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          docker build -t "core-front-build:test" .
