name: Pre-merge checks
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-python@v6
      with:
        python-version: '3.11.2'
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
      with:
        extra_args: "detect-secrets --all-files"
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js 22.x
        uses: actions/setup-node@v6
        with:
          node-version: 22.14.0
      - name: Setup .npmrc
        run: |
          cp .npmrc.template .npmrc && \
          sed -i s/TOKEN_WITH_READ_PACKAGE_PERMISSION/${{ secrets.GITHUB_TOKEN }}/ .npmrc
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
      - name: Install dependencies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test and write coverage
        run: npm run test:coverage
      - name: Run sonarcloud scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarcloud-github-action@ffc3010689be73b8e5ae0c57ce35968afd7909e8 # v5.0.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # obtained from https://sonarcloud.io
      - name: Build docker image
        run: |
          cd "${GITHUB_WORKSPACE}" || exit 1
          docker build -t "core-front-build:test" .
  browser-tests:
    name: Run browser tests
    runs-on: ubuntu-latest
    permissions:
      packages: read
    defaults:
      run:
        shell: bash
        working-directory: browser-tests
    steps:
      - name: Pull repository
        uses: actions/checkout@v5
      - name: Setup .npmrc
        run: |
          cp ../.npmrc.template ../.npmrc && \
          sed -i s/TOKEN_WITH_READ_PACKAGE_PERMISSION/${{ secrets.GITHUB_TOKEN }}/ ../.npmrc
      - name: Run browser tests
        run: docker compose up --exit-code-from browser-tests-tests
      - name: Upload test artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: browser-test-results
          path: ./browser-tests/test-results/
      - name: Stop Docker
        if: ${{ always() }}
        run: docker compose down
