name: Pre-merge checks
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v5
      with:
        python-version: '3.11.2'
    - uses: pre-commit/action@v3.0.1
      with:
        extra_args: "detect-secrets --all-files"
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.16.0
      - name: Login to GDS Dev Dynatrace Container Registry
        uses: docker/login-action@v3
        with:
          registry: khw46367.live.dynatrace.com
          username: khw46367
          password: ${{ secrets.DYNATRACE_PAAS_TOKEN }}
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: npm run lint
      - name: Run test and write coverage
        run: npm run test:coverage
      - name: Run sonarcloud scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # obtained from https://sonarcloud.io
      - name: Build docker image
        run: |
          cd ${GITHUB_WORKSPACE} || exit 1
          docker build -t "core-front-build:test" .
